# Generated by Django 4.1.4 on 2022-12-27 14:57

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import utilities.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0167_module_status'),
        ('extras', '0084_staging'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redfish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('power_usage', models.PositiveSmallIntegerField(blank=True, editable=False, null=True)),
                ('power_state', models.CharField(blank=True, editable=False, max_length=20, null=True)),
                ('health_ok', models.BooleanField(blank=True, editable=False, null=True)),
                ('temp_cpu', models.FloatField(blank=True, editable=False, null=True)),
                ('temp_mb', models.FloatField(blank=True, editable=False, null=True)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('allow_power_state_change', models.BooleanField(blank=True, null=True)),
                ('device', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dcim.device')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
