# Generated by Django 4.1.4 on 2022-12-28 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0063_standardize_description_comments'),
        ('netbox_redfish', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redfish',
            name='ip',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipam.ipaddress'),
        ),
    ]
